from .test_deep_link import TestDjangoDeepLink, TestFlaskDeepLink
from .test_grades import TestGrades
from .test_names_roles import TestNamesRolesProvisioningService
from .test_resource_link import TestDjangoResourceLink, TestFlaskResourceLink
