from .test_deep_link import TestDeepLink
from .test_grades import TestGrades
from .test_names_roles import TestNamesRolesProvisioningService
from .test_resource_link import TestResourceLink
from .test_flask_resource_link import TestFlaskResourceLink
